name: sample_workflow

# Trigger workflow on pushes to the main branch or pull requests
on:
  push:
    branches:
      - main
  pull_request:

# Define the jobs
jobs:
  build:
    # Use the latest Ubuntu environment
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Run a simple script
      - name: Run a hello-world script
        run: echo "Hello, GitHub Actions!"
